#ifndef SKYBOX3D_H
#define SKYBOX3D_H

#include <stdbool.h>
#include <PR/ultratypes.h>
#include <PR/gbi.h>
#include "engine/math_util.h"

/**
 * 3D skybox system.
 *
 * A level-specific sky init function (generated by the css→sm64 pipeline)
 * calls sky3d_register() once with the sky display list and the SM64-space
 * origin/scale of the sky_camera entity.  geo_process_camera() then calls
 * sky3d_geo_inject() each frame to emit the sky view matrix + DL before the
 * regular scene children are traversed.
 *
 * The sky DL must end with gsDPNoOpTag(0x534B5944u) followed by
 * gsSPEndDisplayList().  gfx_pc.c intercepts that tag and calls
 * gfx_rapi->clear_depth_stencil() so subsequent geometry overwrites the sky.
 */

void sky3d_register(Gfx *dl, s32 orig_x, s32 orig_y, s32 orig_z, s32 scale);
void sky3d_clear(void);
void sky3d_geo_inject(Vec3f pos, Vec3f focus, s16 roll);
bool sky3d_is_active(void);
void sky_log(const char *fmt, ...);

#endif /* SKYBOX3D_H */
