#include "src/game/envfx_snow.h"

const GeoLayout surf_rne_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_autumnal_stone_stonewall003c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_autumnal_woods_autumnwood_red_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_brick_adobe003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_concrete_computerwall003a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_concrete_computerwall004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_concrete_concretewall011_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_concrete_forttile003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_concrete_fortwall001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_concrete_fortwall004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_concrete_stonestair001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_construction_wood_constructwood001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_corona_invis_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_corpsypas_acid_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_corpsypas_corpsymoon_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_corpsypas_glasswindow001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_cs_havana_stonefloor007a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_cs_italy_ptilefloor1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_cs_italy_stonewall02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_glass_glasswindow001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_japan_wood_bamboo_floor01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_japan_wood_japanese_bluewood01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_japan_wood_japanese_graywood01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_japan_wood_japanese_pinkwood01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_japan_wood_japanese_redwood01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_japan_wood_japanese_redwood02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_london_metal_london_ibeam_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_london_metal_london_ibeam_001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_medieval_cobblestone005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_medieval_cobblestone006a_trim_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_medieval_woodtrim001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_metal_metalcombine002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_metal_wall027c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_moon_moon_wallpanels03_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_nature_blenddirttojunglegrass001e_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_nature_blenddirttojunglegrass001e_wvt_patch_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_nature_junglegrass001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_nature_junglegrass001c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_nature_junglegrass001d_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_nature_junglegrass001e_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_oceanic_metal_deep_metal_floor_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_pl_barnblitz_woodwall_darkbrown001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_props_hazardstrip001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_r_ne_surfne_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_soho_floortile_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_soho_floortile_001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_soho_floortile_001b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_stardust_bl_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_stardust_lcl_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_stardust_wt_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_stone_stonewall013a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_tile_tilefloor005a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, surf_rne_dl_water_water_hydro_cheap_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, surf_rne_dl_final_revert_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_water_water_well_beneath_vmt_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_winter_cobblewall002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_wood_grain_elevator_facade_14a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_wood_grain_elevator_silo_10b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_wood_wall007a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_wood_western_woodwall002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_wood_wood_bridge001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, surf_rne_dl_final_revert_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout surf_rne_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_ABOVE_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -2, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, surf_rne_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
