#include "levels/de_season/sky/sky_model.inc.c"
#include "levels/de_season/sky/sky_camera.inc.h"

/* forward declaration — defined in src/game/skybox3d.c */
void sky3d_register(Gfx *dl, s32 ox, s32 oy, s32 oz, s32 scale);

static Gfx sky3d_display_list[] = {
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_001_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_002_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_003_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_004_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_005_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_006_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_007_mesh_layer_4),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_008_mesh_layer_4),
    gsSPDisplayList(de_season_sky_dl_final_revert_mesh_layer_4),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_009_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_010_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_011_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_012_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_013_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_014_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_015_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_016_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_017_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_018_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_019_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_020_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_021_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_022_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_023_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_024_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_025_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_026_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_027_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_028_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_029_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_030_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_031_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_032_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_033_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_034_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_035_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_036_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_037_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_038_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_039_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_040_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_041_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_042_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_043_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_044_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_045_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_046_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_047_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_048_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_049_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_050_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_051_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_052_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_053_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_054_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_055_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_056_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_057_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_058_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_059_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_060_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_061_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_062_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_063_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_064_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_065_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_066_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_067_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_068_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_069_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_070_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_071_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_072_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_073_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_074_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_075_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_076_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_077_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_078_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_079_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_080_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_081_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_082_mesh_layer_5),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_083_mesh_layer_5),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_084_mesh_layer_5),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_085_mesh_layer_5),
    gsSPDisplayList(de_season_sky_dl_final_revert_mesh_layer_5),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_086_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_087_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_088_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_089_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_090_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_brick_brickwall014a_091_mesh_layer_1),
    gsSPDisplayList(de_season_sky_dl_final_revert_mesh_layer_1),
    gsDPNoOpTag(0x534B5944u),  /* sky depth-clear marker (SKYD) */
    gsSPEndDisplayList(),
};

s32 de_season_sky_init(UNUSED s16 arg, UNUSED s32 unused) {
    sky3d_register(sky3d_display_list, SKY3D_ORIGIN_X, SKY3D_ORIGIN_Y, SKY3D_ORIGIN_Z, SKY3D_SCALE);
    return 0;
}
