#include "src/game/envfx_snow.h"

const GeoLayout bhop_monster_jam_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_brick_brickfloor001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_brick_brickwall019a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_brick_brickwall036a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_brick_brickwall037a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_brick_brickwall040c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_brick_brickwall052b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_brick_infwlle_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_brick_offwlla_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_building_template003a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_building_template003b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_building_template011m_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_building_template012a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_building_trainstation_template002k_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_building_trainstation_truss_template001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_courtyard_template002a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_courtyard_template002b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_courtyard_template002f_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_building_template_courtyard_template002k_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cable_blue_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cnsc_whiteglass_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_concrete_concreteceiling001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_concrete_concretefloor011a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_concrete_concretewall002b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_concrete_concretewall002c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_concrete_concretewall003a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_concrete_concretewall015c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_concrete_concwsnow01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_concrete_metalwall001b_cheap_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_assault_pavement001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana_dirtfloor009c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana_laundry01b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana_metalwall085a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana_rockgranite02a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana_rockwall011d_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana_white_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana_woodf01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana_woodm_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana__curaila_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_havana__fence3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_italy_black_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_italy_ceiling01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_italy_cobble02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_italy_cobble03_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_italy_picrate2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_italy_ptilefloor1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_italy_pwood1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_italy_stonewall02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_cs_italy_yellow_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_aztec_wood_plank_7_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_cbble_cratebig01c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_cbble_grassfloor01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_cbble_grounddirt_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_cbble_woodceiling01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_bricketrima_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_brickfbrkn_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_brickfdoorc_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_cnstrcttarp_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_cnstrcttarpb_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_curtain01b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_interiortile01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_rockf_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_rockf_blend_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_wall02a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_wall03b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_chateau_woodm_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_dust_groundsand_blend_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_dust_marketwall05b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_dust_residbwall03a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_dust_rockwall01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_dust_templewall02b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_dust_tilefloor02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_nuke_nukblenddirtgrass_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_nuke_nuke_metalgrate_01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_piranesi_pi_wood1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_tides_blend_concrete_dirt_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_tides_tides_roof_1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_train_blendgrassdirt001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_de_train_blendgraveldirt001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decal_crater001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decalindustrialnumber01a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decalindustrialnumber02a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decalindustrialnumber03a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decalindustrialnumber04b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decalindustrialnumber05c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decalindustrialnumber06b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decalindustrialnumber07c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decalindustrialnumber08b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_decalmetalhatch005a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_italy_flag_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_armory_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_bag_of_milk_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_big_ben_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_can_of_soup_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_cool_names_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_credits_lowres_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_decoy_fascist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_dinosaur_rider_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_dinosaurs_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_earth_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_earth_explode_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_end_room_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_fighters_1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_fighters_2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_fighters_3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_flag_brazil_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_flag_canada_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_flag_china_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_flag_egypt_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_flag_england_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_flag_france_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_flag_germany_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_flag_russia_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_golden_speakers_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_jam_on_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_krazed_dog_anim_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_leaning_tower_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_limo_small_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_monster_jam_rules_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_monstertruck1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_moon_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_moose_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_movie_marquee_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_no_jamming_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_palm_leaves_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_paparazzi_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_rocky_bullwinkle_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_secret_room_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_sign_2s_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_sniper_bear_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_sphinx_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_tutorial_room_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_velvet_rope_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_vip_lounge_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_wall_of_oppression_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_world_map_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_decals_monsterjam_you_are_here_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_dev_dev_lowerwallmetal01d_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_dev_valuesand20_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_dev_valuesand50_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_effects_bubble_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_environment_maps_pipeset_metal_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_ground_blendsnow_tracks_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_halflife__ladder2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_kc_main_marblefloor14_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_lights_fluorescentcool003a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_liquids_militiawater_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_liquids_militiawaterbeneath_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_liquids_water_dx70_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_metal_citadel_metalwall090a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_metal_metalfloor005a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_metal_metalhull003a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_metal_metalladder001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_metal_metalrail013c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_metal_prodcaution_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_metal_proddoora_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_models_de_corse_tree04c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_models_props_canal_rock_riverbed01a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_models_props_de_inferno_pillarc_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_models_props_de_inferno_tree_group10_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_models_props_de_inferno_tree_group11_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_models_props_de_inferno_tree_group4_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_models_props_de_inferno_tree_group5_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_models_props_de_inferno_tree_group8_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_models_props_de_inferno_woodfloor008a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_models_props_de_nuke_lifepreserver_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_models_props_de_port_clouds2_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_models_props_debris_tilewall009b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_models_props_foliage_oak_tree01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_models_props_lab_warp_sheet_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blenddirtdirt001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blenddirtgrass006a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blendgrassgrass001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blendgrassgravel001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blendmilground004_2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blendmilground008_2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blendmilground008_4_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blendmilground008_8b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blendmilground008b_2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blendmilground011_2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_blendmuddirt001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_inftreelinea_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_milground012_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_milmountains001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_milmountains002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_miltree001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_miltree002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_miltree003_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_miltree004_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_miltree005_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_miltree007_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_sandfloor010a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_nature_treeline001a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_nature_water_dx70_beneath_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bhop_monster_jam_dl_final_revert_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_plaster_plasterceiling002b_mesh_layer_1),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 11744, 10496, -7424, 0, 0, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 7680, 7424, -1792, 0, 0, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 7274, 7424, -6398, 0, 0, 90),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 7904, 7605, -3328),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8266, 7569, -3210, 0, 0, 105),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8953, 7569, -3281, 0, 0, 75),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8681, 7569, -3329, 0, 0, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8583, 7569, -1183, 0, 0, -90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8950, 7569, -1318, 0, 0, -75),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8263, 7569, -1247, 0, 0, -105),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 9920, 7555, -4480),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 9114, 7553, -2230, 0, 0, 15),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 9249, 7553, -1863),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 9185, 7553, -1543, 0, 0, -15),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 9003, 7553, -6196),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8128, 7552, -4928, 0, 0, -90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8124, 7547, -2950, 0, 0, -90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 8132, 7547, -1390, 0, 0, -90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 9012, 7552, -6644, 0, 0, 90),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 10092, 7552, -5332),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 12384, 7684, 10240),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 12352, 7936, 10240, -180, 0, 0),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 12337, 8000, 9728, 0, -180, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 12364, 7584, 9696, 0, 0, -90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 12256, 8100, 10720, 0, 0, -180),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 11924, 8104, 9060, 0, 0, -150),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1256, 10225, 4320),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -512, 10492, 3888, 0, 0, -180),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -896, 10283, 4288, 0, 0, -180),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -864, 10113, 3712, 0, 0, -180),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 3040, 10384, 4944, 0, 0, -180),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 7168, 10113, 7672, 0, 0, 90),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -3316, 16534, 592),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -3047, 17584, 3911),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -7232, 17584, 1984),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -11008, 10466, 1536),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19712, 9924, -2432, 0, 0, -90),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12672, 10508, -3456),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -17536, 10554, -3200, 0, 0, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -17408, 10554, -1536, 0, 0, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -14080, 15488, 3328, 0, 0, 90),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -18368, 16128, -27392),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -16896, 10752, -2880, 0, 0, -90),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -14912, 10659, -4032),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -10304, 10784, -3456, 0, 0, -180),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -17056, 10752, -2784),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 9632, 7696, 6353, 0, 0, -180),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 9104, 7696, 6353, 0, 0, -180),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -2128, 12544, 16368, 0, 0, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -10040, 10888, -4072, 0, 0, -180),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -11728, 15936, -3968, 0, 0, -180),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1248, 10113, 4608),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1248, 10414, 3952),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -1152, 10551, 3744, 0, 0, -90),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -3972, 16534, 480),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12576, 15856, 3120, 0, 0, 135),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13312, 15744, 3520, -60, 0, -180),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13104, 15744, 3392, 0, 0, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -11776, 15856, 944, 0, 0, -165),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12071, 15936, 1914, 0, 0, -45),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -11984, 15936, 2416, 0, 0, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12240, 15536, 2720, 0, 0, 120),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 9588, 7617, 5521, 0, 0, 30),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12864, 15776, 3296, 0, 0, 90),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -11856, 10720, -4224, 0, 0, 45),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12416, 10690, -192),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12608, 10880, 1088),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -10816, 10880, 3264, 0, 0, 20),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12336, 10688, -640),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12288, 10688, 320),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12544, 10880, 1536),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12352, 10624, 896),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12416, 10944, 896),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12480, 11008, 1152),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12672, 10880, 2176),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -12352, 10560, 3136),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12606, 10560, 2884, 0, 0, 45),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 4352, 7552, 6976, 0, 0, 15),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 10176, 7577, 6944, 0, 0, 15),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -6032, 7440, -3056),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5024, 7543, -6608, 0, 0, 15),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_props_carpetfloor008a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_props_metalcrate002b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_props_signstreet004a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_props_tarpaperroof002a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_sprites_sprite_fire01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_sprites_yelflare2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_stone_infwllftopedge_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_stone_marblefloor001b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_stone_stonewall014a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_stone_stonewall024a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_stone_stonewall029a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_wood_cabinets01a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bhop_monster_jam_dl_wood_inffence01_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bhop_monster_jam_dl_final_revert_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_wood_infwoodfloor008a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_wood_milflr002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_wood_wooddoor007a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_wood_woodfloor008a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bhop_monster_jam_dl_final_revert_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bhop_monster_jam_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_ABOVE_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -2, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bhop_monster_jam_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
