#include "src/game/envfx_snow.h"

const GeoLayout kz_bhop_liminal_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_73_naturalselection_rock_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_73_naturalselection_trim_012_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_73_naturalselection_wall_019_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_brick_brickwall_baggage_stripe_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_concrete1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_concrete14_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_concrete17_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_concrete2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_concrete6_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_concrete7_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_concretewall010a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_hr_c_hr_concrete_wall_painted_002_green_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_tiles11_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_tiles9_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_underground_concrete_ceiling001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_concrete_white_flat_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_cs_havana_ceiling01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_custom_bhop_block_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_custom_bhop_block_purple_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_custom_bhop_block_purple_rad_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_custom_bhop_block_single_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_custom_bhop_blocknolight_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_custom_fogbg_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_custom_pinklights_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_de_cbble_trim03_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_de_chateau_interiortile02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_de_chateau_rockf_blend_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_de_nuke_hr_nuke_officelight_emitter_001_blue_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_dev_dev_hazzardstripe01a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_dev_dev_measuregeneric02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_dev_dev_measuregeneric21_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_dev_dev_measuregeneric40_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_dev_dev_measuregeneric46_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_dev_nyro_dev_blue_e_05_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_dev_nyro_dev_blue_e_06_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_dev_nyro_dev_cyan_b_07_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_dev_nyro_dev_red_a_02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_egypt_wall_stone2_plain_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_fda_tile_tile_07_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_fool_homefront_terrain_temperate_grass_2b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_fool_re8_wood_wood_planks_01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_fool_wolfensteinii_floor_tiles_checkered_hotel_01_albedo_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_fool_wolfensteinii_wood_wood_woodtrim_02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_glass_xtre_marked_glass_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_icecreamlock_darkglass_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_kz_bhop_genkai_other_trigger_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_liquids_metal_black_wall_metal_004b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_materials_realworldtextures2_ground_grass_05_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_metal_metaldoor032a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_metal_prodventa_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_motel_hotel_carpet001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_nature_blendgrassdirt01_noprop_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_nature_water_coast01_beneath_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_nature_water_coast_custom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_nature_water_coast_custom_dark_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_plar_colors_red_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_plar_fading_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_plaster_plasterceiling003a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_plaster_plasterwall043c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_plaster_wallpaper003b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_portalhack_portalhack_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_realworldtextures2_tile_plastic_tile_01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_realworldtextures_floor_mixtile_gray_red_border_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_realworldtextures_floor_mixtile_solid_black_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_realworldtextures_new_wall_a02_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_realworldtextures_newer_3_tile_3_06_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_saspatoon_carpet_carpetgreen_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_saspatoon_carpet_carpetwhite_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_tile_tilewall006a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_tile_tilewall006b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_tile_tilewall006c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_tile_underground_white_tile002a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_wall_wall_stone_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_wood_wood_fine_01_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_bhop_liminal_dl_final_revert_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kz_bhop_liminal_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_ABOVE_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -2, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, kz_bhop_liminal_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
