#ifndef REMOVED_LEVEL_STUBS_H
#define REMOVED_LEVEL_STUBS_H

#include <PR/ultratypes.h>
#include <PR/gbi.h>

#include "types.h"

struct Painting;

extern const Gfx castle_grounds_seg7_dl_0700EA58[];
extern const Gfx castle_grounds_seg7_us_dl_0700F2E8[];
extern const Gfx dl_castle_lobby_wing_cap_light[];
extern const Gfx dl_flying_carpet_begin[];
extern const Gfx dl_flying_carpet_model_half[];
extern const Gfx dl_flying_carpet_end[];
extern const Gfx dl_cake_end_screen[];

extern const Collision wf_seg7_collision_rotating_platform[];
extern const Collision wdw_seg7_collision_070186B4[];
extern const Collision wdw_seg7_collision_07018528[];
extern const Collision wf_seg7_collision_tumbling_bridge[];
extern const Collision bbh_seg7_collision_07026B1C[];
extern const Collision lll_seg7_collision_0701D21C[];
extern const Collision bitfs_seg7_collision_07015288[];
extern const Collision bowser_3_seg7_collision_07004B94[];
extern const Collision bowser_3_seg7_collision_07004C18[];
extern const Collision bowser_3_seg7_collision_07004C9C[];
extern const Collision bowser_3_seg7_collision_07004D20[];
extern const Collision bowser_3_seg7_collision_07004DA4[];
extern const Collision bowser_3_seg7_collision_07004E28[];
extern const Collision bowser_3_seg7_collision_07004EAC[];
extern const Collision bowser_3_seg7_collision_07004F30[];
extern const Collision bowser_3_seg7_collision_07004FB4[];
extern const Collision bowser_3_seg7_collision_07005038[];
extern const Collision inside_castle_seg7_collision_ddd_warp[];
extern const Collision inside_castle_seg7_collision_ddd_warp_2[];
extern const Collision bob_seg7_collision_gate[];
extern const Collision hmc_seg7_collision_0702B65C[];

extern void *ccm_seg7_trajectory_snowman;
extern void *inside_castle_seg7_trajectory_mips;
extern const s16 removed_level_trajectory_stub[];

extern struct Painting bob_painting;
extern struct Painting ccm_painting;
extern struct Painting cotmc_painting;
extern struct Painting wf_painting;
extern struct Painting jrb_painting;
extern struct Painting lll_painting;
extern struct Painting ssl_painting;
extern struct Painting hmc_painting;
extern struct Painting ddd_painting;
extern struct Painting wdw_painting;
extern struct Painting thi_tiny_painting;
extern struct Painting ttm_painting;
extern struct Painting ttc_painting;
extern struct Painting sl_painting;
extern struct Painting thi_huge_painting;
extern struct Painting ttm_slide_painting;

extern u8 removed_level_u8_stub[];
extern s16 removed_level_s16_stub[];
extern Gfx removed_level_gfx_stub[];

extern const s16 flying_carpet_static_vertex_data[];

#define bitdw_seg7_collision_0700F688 wf_seg7_collision_rotating_platform
#define bitdw_seg7_collision_0700F70C wf_seg7_collision_rotating_platform
#define bitdw_seg7_collision_0700F7F0 wf_seg7_collision_rotating_platform
#define bitdw_seg7_collision_0700F898 wf_seg7_collision_rotating_platform
#define bitdw_seg7_collision_0700F91C wf_seg7_collision_rotating_platform
#define bitdw_seg7_collision_0700FA3C wf_seg7_collision_rotating_platform
#define bitdw_seg7_collision_0700FB5C wf_seg7_collision_rotating_platform
#define bitdw_seg7_collision_0700FC7C wf_seg7_collision_rotating_platform
#define bitdw_seg7_collision_0700FD9C wf_seg7_collision_rotating_platform
#define bitfs_seg7_collision_07015124 wf_seg7_collision_rotating_platform
#define bitfs_seg7_collision_07015714 wf_seg7_collision_rotating_platform
#define bitfs_seg7_collision_07015768 wf_seg7_collision_rotating_platform
#define bitfs_seg7_collision_070157E0 wf_seg7_collision_rotating_platform
#define bitfs_seg7_collision_07015928 wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701A9A0 wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701AA0C wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701AA84 wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701AC28 wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701ACAC wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701AD54 wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701ADD8 wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701AE5C wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701B0D4 wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701B26C wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701B404 wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701B59C wf_seg7_collision_rotating_platform
#define bits_seg7_collision_0701B734 wf_seg7_collision_rotating_platform
#define bob_seg7_collision_bridge wf_seg7_collision_rotating_platform
#define ccm_seg7_collision_070163F8 wf_seg7_collision_rotating_platform
#define rr_seg7_collision_07029038 wf_seg7_collision_rotating_platform
#define rr_seg7_collision_07029508 wf_seg7_collision_rotating_platform
#define rr_seg7_collision_070295F8 wf_seg7_collision_rotating_platform
#define rr_seg7_collision_0702967C wf_seg7_collision_rotating_platform
#define rr_seg7_collision_07029750 wf_seg7_collision_rotating_platform
#define rr_seg7_collision_07029858 wf_seg7_collision_rotating_platform
#define rr_seg7_collision_07029924 wf_seg7_collision_rotating_platform
#define rr_seg7_collision_07029C1C wf_seg7_collision_rotating_platform
#define rr_seg7_collision_07029FA4 wf_seg7_collision_rotating_platform
#define rr_seg7_collision_0702A32C wf_seg7_collision_rotating_platform
#define rr_seg7_collision_0702A6B4 wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_07028274 wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_070282F8 wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_07028370 wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_070284B0 wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_07014F70 wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_07015008 wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_070152B4 wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_070153E0 wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_07015584 wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_07015650 wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_07015754 wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_070157D8 wf_seg7_collision_rotating_platform
#define vcutm_seg7_collision_0700AC44 wf_seg7_collision_rotating_platform

#define bbh_seg7_collision_coffin wf_seg7_collision_rotating_platform
#define bbh_seg7_collision_haunted_bookshelf wf_seg7_collision_rotating_platform
#define bbh_seg7_collision_merry_go_round wf_seg7_collision_rotating_platform
#define bbh_seg7_collision_mesh_elevator wf_seg7_collision_rotating_platform
#define bbh_seg7_collision_staircase_step wf_seg7_collision_rotating_platform
#define bbh_seg7_collision_tilt_floor_platform wf_seg7_collision_rotating_platform
#define bitdw_seg7_collision_moving_pyramid wf_seg7_collision_rotating_platform
#define bitfs_seg7_collision_inverted_pyramid wf_seg7_collision_rotating_platform
#define bitfs_seg7_collision_sinking_cage_platform wf_seg7_collision_rotating_platform
#define bitfs_seg7_collision_sinking_platform wf_seg7_collision_rotating_platform
#define bitfs_seg7_collision_squishable_platform wf_seg7_collision_rotating_platform
#define bob_seg7_collision_chain_chomp_gate wf_seg7_collision_rotating_platform
#define bowser_2_seg7_collision_tilting_platform wf_seg7_collision_rotating_platform
#define castle_grounds_seg7_anims_flags wf_seg7_collision_rotating_platform
#define castle_grounds_seg7_collision_cannon_grill wf_seg7_collision_rotating_platform
#define castle_grounds_seg7_collision_moat_grills wf_seg7_collision_rotating_platform
#define ddd_seg7_collision_bowser_sub_door wf_seg7_collision_rotating_platform
#define ddd_seg7_collision_submarine wf_seg7_collision_rotating_platform
#define hmc_seg7_collision_controllable_platform wf_seg7_collision_rotating_platform
#define hmc_seg7_collision_controllable_platform_sub wf_seg7_collision_rotating_platform
#define hmc_seg7_collision_elevator wf_seg7_collision_rotating_platform
#define inside_castle_seg7_collision_floor_trap wf_seg7_collision_rotating_platform
#define inside_castle_seg7_collision_star_door wf_seg7_collision_rotating_platform
#define inside_castle_seg7_collision_water_level_pillar wf_seg7_collision_rotating_platform
#define jrb_seg7_collision_floating_box wf_seg7_collision_rotating_platform
#define jrb_seg7_collision_floating_platform wf_seg7_collision_rotating_platform
#define jrb_seg7_collision_in_sunken_ship wf_seg7_collision_rotating_platform
#define jrb_seg7_collision_in_sunken_ship_2 wf_seg7_collision_rotating_platform
#define jrb_seg7_collision_in_sunken_ship_3 wf_seg7_collision_rotating_platform
#define jrb_seg7_collision_pillar_base wf_seg7_collision_rotating_platform
#define jrb_seg7_collision_rock_solid wf_seg7_collision_rotating_platform
#define lll_seg7_collision_drawbridge wf_seg7_collision_rotating_platform
#define lll_seg7_collision_falling_wall wf_seg7_collision_rotating_platform
#define lll_seg7_collision_floating_block wf_seg7_collision_rotating_platform
#define lll_seg7_collision_hexagonal_platform wf_seg7_collision_rotating_platform
#define lll_seg7_collision_inverted_pyramid wf_seg7_collision_rotating_platform
#define lll_seg7_collision_octagonal_moving_platform wf_seg7_collision_rotating_platform
#define lll_seg7_collision_pitoune wf_seg7_collision_rotating_platform
#define lll_seg7_collision_puzzle_piece wf_seg7_collision_rotating_platform
#define lll_seg7_collision_rotating_fire_bars wf_seg7_collision_rotating_platform
#define lll_seg7_collision_rotating_platform wf_seg7_collision_rotating_platform
#define lll_seg7_collision_sinking_pyramids wf_seg7_collision_rotating_platform
#define lll_seg7_collision_slow_tilting_platform wf_seg7_collision_rotating_platform
#define lll_seg7_collision_wood_piece wf_seg7_collision_rotating_platform
#define rr_seg7_collision_donut_platform wf_seg7_collision_rotating_platform
#define rr_seg7_collision_elevator_platform wf_seg7_collision_rotating_platform
#define rr_seg7_collision_pendulum wf_seg7_collision_rotating_platform
#define rr_seg7_collision_rotating_platform_with_fire wf_seg7_collision_rotating_platform
#define sl_seg7_collision_pound_explodes wf_seg7_collision_rotating_platform
#define sl_seg7_collision_sliding_snow_mound wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_0702808C wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_grindel wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_pyramid_elevator wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_pyramid_top wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_spindel wf_seg7_collision_rotating_platform
#define ssl_seg7_collision_tox_box wf_seg7_collision_rotating_platform
#define thi_seg7_collision_top_trap wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_clock_main_rotation wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_clock_pendulum wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_clock_platform wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_rotating_clock_platform2 wf_seg7_collision_rotating_platform
#define ttc_seg7_collision_sliding_surface wf_seg7_collision_rotating_platform
#define ttm_seg7_collision_pitoune_2 wf_seg7_collision_rotating_platform
#define ttm_seg7_collision_podium_warp wf_seg7_collision_rotating_platform
#define ttm_seg7_collision_ukiki_cage wf_seg7_collision_rotating_platform
#define wdw_seg7_collision_arrow_lift wf_seg7_collision_rotating_platform
#define wdw_seg7_collision_express_elevator_platform wf_seg7_collision_rotating_platform
#define wdw_seg7_collision_rect_floating_platform wf_seg7_collision_rotating_platform
#define wdw_seg7_collision_square_floating_platform wf_seg7_collision_rotating_platform
#define wf_seg7_collision_breakable_wall wf_seg7_collision_rotating_platform
#define wf_seg7_collision_breakable_wall_2 wf_seg7_collision_rotating_platform
#define wf_seg7_collision_bullet_bill_cannon wf_seg7_collision_rotating_platform
#define wf_seg7_collision_clocklike_rotation wf_seg7_collision_rotating_platform
#define wf_seg7_collision_kickable_board wf_seg7_collision_rotating_platform
#define wf_seg7_collision_large_bomp wf_seg7_collision_rotating_platform
#define wf_seg7_collision_platform wf_seg7_collision_rotating_platform
#define wf_seg7_collision_sliding_brick_platform wf_seg7_collision_rotating_platform
#define wf_seg7_collision_small_bomp wf_seg7_collision_rotating_platform
#define wf_seg7_collision_tower wf_seg7_collision_rotating_platform
#define wf_seg7_collision_tower_door wf_seg7_collision_rotating_platform

#define bitfs_seg7_trajectory_070159AC removed_level_trajectory_stub
#define bob_seg7_metal_ball_path0 removed_level_trajectory_stub
#define bob_seg7_metal_ball_path1 removed_level_trajectory_stub
#define bob_seg7_trajectory_koopa removed_level_trajectory_stub
#define ccm_seg7_trajectory_0701669C removed_level_trajectory_stub
#define ccm_seg7_trajectory_penguin_race removed_level_trajectory_stub
#define hmc_seg7_trajectory_0702B86C removed_level_trajectory_stub
#define jrb_seg7_trajectory_unagi_1 removed_level_trajectory_stub
#define jrb_seg7_trajectory_unagi_2 removed_level_trajectory_stub
#define lll_seg7_trajectory_0702856C removed_level_trajectory_stub
#define lll_seg7_trajectory_07028660 removed_level_trajectory_stub
#define rr_seg7_trajectory_0702EC3C removed_level_trajectory_stub
#define rr_seg7_trajectory_0702ECC0 removed_level_trajectory_stub
#define rr_seg7_trajectory_0702ED9C removed_level_trajectory_stub
#define rr_seg7_trajectory_0702EEE0 removed_level_trajectory_stub
#define thi_seg7_trajectory_koopa removed_level_trajectory_stub
#define ttm_seg7_trajectory_070170A0 removed_level_trajectory_stub

#endif
